image:
  name: node:18
  entrypoint: [""]

variables:
  GIT_DEPTH: 0  # shallow clone 방지

stages:
  - build
  - mirror

pages:
  stage: build
  script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm install
    - pnpm build
    - pnpm generate
    - mv .output/public public  # Nuxt3 기준 출력 디렉토리
  artifacts:
    paths:
      - public
  only:
    - main
  tags:
    - board

mirror_to_github:
  stage: mirror
  script:
    - git config --global user.name "ChaHyunHo"
    - git config --global user.email "chamym@naver.com"
    - git remote add github https://ChaHyunHo:${GITHUB_TOKEN}@github.com/ChaHyunHo/vue_tutorial.git
    - git fetch origin main
    - git checkout -B main origin/main
    - git push -f github main
  only:
    - main
  tags:
    - mirror